apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: svc-taxi-secret
  namespace: staging
spec:
  encryptedData:
    webhook-secret-key: AgB1Yci8W8DyZAT9bnod64DazLENKHUrC4630V/sHebKrbfiXtI9S2Xl9l2sVqQvum/h+NWnn7qLuhVwu7sel57UAlzCNaiZpY1u7dY6L8l+fazxf4BbvHI7J6rNYJk036l3bmk5cItzBK8UlBeDGOZ+KKED+ry12W3EKxY6nFhhqNitlQL6ZCfAQ5Wb8mMetjC3ttvdbfGi5LWkazyP65XPzY+1S6ok9On3bo3ouVlfbAGVqWvnxQkhW6AHlRhvkKYC03pXAnyjUrCgaQSpU2aEIKrrrew4vwHpv++ctWoLZVclLFPw64uzh2cU7sayfXuEYEMA04rZxa2zo5IKOR+zlqKkPgjALzs9oV0Sz2OgKyaNoYNiOtj4STXugHC7+D1hczE1eRx30aBaxUo3EiDQC1Ty3j5iOUnZEUQZvW2Xaz4PhU7quBrY/cdTxBYfKp+IGrpXxSW7SDxBuDzMd18b+DZVMbnmhIlObU2s+UTczbBC5cnZ52gfKPbO1DXj03MuFEqfUdwg4zHu3uss982+KMoP7wq6WcmcWEyc0y9dujtq6eqAm/lVLwNtoZklSxU08j8uVod18cSsvRJbmin3TLeej6rECOsR6oKqicF2CcuoNynJ2kTBCxcAHiNDayNzeudNCG7fBpBKASLegkRWqlG0qP9fQTdxkSLm4uiHoTO3XlrUVgVeRH48PlilOncoUKQ=
  template:
    metadata:
      creationTimestamp: null
      name: svc-taxi-secret
      namespace: staging
    type: Opaque
status: {}
