bases:
- ../base
patchesJson6902:
- path: eventlistener_patch.yaml
  target:
    group: tekton.dev
    kind: EventListener
    name: cicd-event-listener
    version: v1alpha1
- path: pipeline_patch.yaml
  target:
    group: tekton.dev
    kind: Pipeline
    name: app-cd-pipeline
    version: v1alpha1
