apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAfVNO4lVYZaTq8drLWQq1P8B5fJ2RRu1tuwWMm+tgU0svuQ76pQ4WZ1xZ2uY+W41NCun8V6J/Cjf1rb3g0t10t0JUSfVXzClaRRTc8brFoH+OPIaDTsbs6P27S60UTr86F8B36Fu2An5oLMMIZ5pZ90AaPU6mXPqh6qCvqM7pbyBFLoGuWPnN8xFpwcvJ3V/jsaOFtGtTxWJVTc61iHZtRWzOx10/Pjgb6kC+3sxj0LcALhya6jrFog0Z6UtY5FKDUWNRQDl57bvbgOrbRf37YYF9oJ2ceywlS4P/ZqVk9D5k6xEqP879upyXCyuJhmA1zF84IgHx5L1awlMzT696YK0NjzlMXRV1AXoVKZUCrjMTEENT+iqFWh2ainj1u8gahBJxjWRD4AKWs9W4L7G3eCpOD7zRB5RRYNFrkrcUoNuFff8WMX9XEciDxkoiZ5tUWi0Kfc8iP8hNJ091h2dUJ0EDIwTsNxHy8iHVGcqW1hHAYEe3P5Oqp1Mvnw/vIvzxVDz4JkbpoALFK1xfCCKcgyQOsKSpr5albD67Tc5hKE9tej2HMqWegwd32gLjSeWj5e9UGm2Wjauw5zKLHknt3YQgX0u+tMb+uaTbtDR6GfL4fYok4MK/5750GbjTCaw3JIlmXQweGricSpb26yEfr7lf7sbh+MCutlKL0WcGnKovt9lZwWvo+M3CH+tbrRMZCcN0=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
